"""Name migr

<<<<<<< HEAD:alembic/versions/c7d0138792f8_name_migr.py
Revision ID: c7d0138792f8
Revises: 
Create Date: 2024-02-06 17:58:06.981961
=======
Revision ID: 11b8ed05e7ec
Revises: 
Create Date: 2024-02-06 17:34:31.197199
>>>>>>> a1944e6f3ff5b5d7fd7632bd2982b407fc838f26:alembic/versions/d0dc0857ec70_first_migration.py

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
<<<<<<< HEAD:alembic/versions/c7d0138792f8_name_migr.py
revision: str = 'c7d0138792f8'
=======
revision: str = '11b8ed05e7ec'
>>>>>>> a1944e6f3ff5b5d7fd7632bd2982b407fc838f26:alembic/versions/d0dc0857ec70_first_migration.py
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
<<<<<<< HEAD:alembic/versions/c7d0138792f8_name_migr.py
    sa.Column('user_name', sa.String(length=100), nullable=False),
=======
>>>>>>> a1944e6f3ff5b5d7fd7632bd2982b407fc838f26:alembic/versions/d0dc0857ec70_first_migration.py
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
<<<<<<< HEAD:alembic/versions/c7d0138792f8_name_migr.py
    sa.UniqueConstraint('user_name')
=======
>>>>>>> a1944e6f3ff5b5d7fd7632bd2982b407fc838f26:alembic/versions/d0dc0857ec70_first_migration.py
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
